accounts/urls.py
from . import views
from django.urls import path

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follows/', views.follows, name='follows'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from posts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.redirect_index),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from . import views
from django.urls import path

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:post_pk>/', views.detail, name='detail'),
    path('<int:post_pk>/answer/<str:answer>', views.answer, name='answer'),
    path('<int:post_pk>/likes/', views.post_like, name='post_like'),
    path('<int:post_pk>/comments/', views.comment_create, name='comment_create'),
    path('<int:post_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:post_pk>/comments/<int:comment_pk>/likes/', views.comment_like, name='comment_like'),
    path('<int:post_pk>/comments/<int:comment_pk>/update/', views.comment_update, name='comment_update'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')

posts/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=20)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')
    select1_content = models.CharField(max_length=20)
    select2_content = models.CharField(max_length=20)
    select1_user = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='select1')
    select2_user = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='select2')
    select1_image = ProcessedImageField(blank=True, upload_to='select_image',
                                        processors=[ResizeToFill(100,100)],
                                        format='PNG',
                                        options={'quality': 80})
    select2_image = ProcessedImageField(blank=True, upload_to='select_image',
                                        processors=[ResizeToFill(100,100)],
                                        format='PNG',
                                        options={'quality': 80})
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField()
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_comments')

accounts/forms.py
from django.contrib.auth import get_user_model, password_validation
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm, AuthenticationForm, UsernameField
from django import forms
from django.utils.translation import gettext_lazy as _

class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(
        label='닉네임',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'style': 'width:40%; min-width:300px;',
                'placeholder': '닉네임을 입력해주세요',
            }
        ),
        max_length=150,
        help_text=_('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
    )
    
    email = forms.EmailField(
        label='이메일',
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control',
                'style': 'width:40%; min-width:300px;',
                'placeholder': '이메일을 입력해주세요',
            }
        )
    )

    password1 = forms.CharField(
        label='비밀번호',
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'style': 'width:40%; min-width:300px;',                
                'placeholder': '비밀번호를 입력해주세요',
            }
        ),
        help_text=password_validation.password_validators_help_text_html(),
    )

    password2 = forms.CharField(
        label='비밀번호 확인',
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'style': 'width:40%; min-width:300px;',                
                'placeholder': '비밀번호를 다시 입력해주세요',
            }
        )
    )
    
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('username', 'email', 'password1', 'password2', )

class CustomUserChangeForm(UserChangeForm):
    password = None

    username = forms.CharField(
        label='닉네임',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'style': 'width:40%; min-width:300px;',
                'placeholder': '닉네임을 입력해주세요',
            }
        )
    )
    
    email = forms.EmailField(
        label='이메일',
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control',
                'style': 'width:40%; min-width:300px;',
                'placeholder': '이메일을 입력해주세요',
            }
        )
    )

    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = (
            'username',
            'email',
        )

class CustomPasswordChangeForm(PasswordChangeForm):

    old_password = forms.CharField(
        strip=False,
        label='기존 비밀번호',
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "current-password",
                "autofocus": True,
                'class': 'form-control',
                'style': 'width:40%; min-width:300px;',                
                'placeholder': '현재 비밀번호를 입력해주세요',
            }
        )
    )

    new_password1 = forms.CharField(
        label='새 비밀번호',
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "new-password",
                'class': 'form-control',
                'style': 'width:40%; min-width:300px;',                
                'placeholder': '새 비밀번호를 입력해주세요',
            }
        ),
        help_text=password_validation.password_validators_help_text_html(),
    )

    new_password2 = forms.CharField(
        label='새 비밀번호 재입력',
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "new-password",
                'class': 'form-control',
                'style': 'width:40%; min-width:300px;',                
                'placeholder': '새 비밀번호를 다시 입력해주세요',
            }
        )
    )

class CustomAuthenticationForm(AuthenticationForm):
    username = UsernameField(
        label='닉네임',
        widget=forms.TextInput(
            attrs={
                "autofocus": True,
                'class': 'form-control',
                'style': 'width:40%; min-width:300px;',
                'placeholder': '닉네임을 입력해주세요',
            }
        )
    )

    password = forms.CharField(
        label='비밀번호',
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "current-password",
                'class': 'form-control',
                'style': 'width:40%; min-width:300px;',                
                'placeholder': '비밀번호를 입력해주세요',
            }
        )
    )

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import login_required
from .forms import CustomUserCreationForm, CustomUserChangeForm, CustomPasswordChangeForm, CustomAuthenticationForm
from django.contrib.auth import get_user_model
from django.contrib.auth import update_session_auth_hash

# Create your views here.
def login(request):
    if request.user.is_authenticated:
        return redirect('posts:index')
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('posts:index')
        is_get = False
    else:
        form = CustomAuthenticationForm()
        is_get = True


    context = {
        'form': form,
        'is_get': is_get,
    }
    return render(request, 'accounts/login.html', context)

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('posts:index')
        is_get = False
    else:
        form = CustomUserCreationForm()
        is_get = True
    
    context = {
        'form': form,
        'is_get': is_get,
    }
    return render(request, 'accounts/signup.html', context)

@login_required
def logout(request):
    auth_logout(request)
    return redirect('posts:index')

def profile(request, username):
    User = get_user_model()
    person = User.objects.get(username=username)
    context = {
        'person': person,
    }
    return render(request, 'accounts/profile.html', context)

@login_required
def follows(request, user_pk):
    User = get_user_model()
    person = User.objects.get(pk=user_pk)
    if request.user != person:
        if person.followers.filter(pk=request.user.pk).exists():
            person.followers.remove(request.user)
        else:
            person.followers.add(request.user)
    return redirect('accounts:profile', person.username)

@login_required
def update(request):
    User = get_user_model()
    user = User.objects.get(pk=request.user.pk)
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=user)
        is_get = False
        if form.is_valid():
            form.save()
            return redirect('accounts:profile', user.username)
    else:
        form = CustomUserChangeForm(instance=user)
        is_get = True

    context = {
        'form': form,
        'is_get': is_get,
    }
    return render(request, 'accounts/update.html', context)

@login_required
def change_password(request):
    if request.method == 'POST':
        form = CustomPasswordChangeForm(request.user, request.POST)
        is_get = False
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('accounts:profile', user.username)
        
    else:
        form = CustomPasswordChangeForm(request.user)
        is_get = True
    context = {
        'form': form,
        'is_get': is_get
    }
    return render(request, 'accounts/change_password.html', context)

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block content %}
<h1 class="mb-3">Change Password</h1>
<form action="{% url 'accounts:change_password' %}" method="post">
  {% csrf_token %}

  {% for field in form %}
    <div class="mb-3">
      {% if field.errors and not is_get %}
        {{ field.errors }}
      {% endif %}
      <label for="id_{{ field.name }}" class="form-label">{{ field.label }}</label>
      {{ field }}
      {% if field.help_text %}
      {{ field.help_text }}
      {% endif %}
    </div>
  {% endfor %}
  <input type="submit" value="Change" class="btn btn-primary">
</form>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
  <h1>Login</h1>
  <form action="{% url 'accounts:login' %}" method="POST">
    {% csrf_token %}

    {% if not form.is_valid and not is_get %}
      {% for error in form.get_invalid_login_error %}
        <p>{{ error}}</p>
      {% endfor %} 
    {% endif %}
    
    {% for field in form %}
    <div class="mb-3">
      <label for="id_{{ field.name }}" class="form-label">{{ field.label }}</label>
      {{ field }}
      {% if field.help_text %}
      {{ field.help_text }}
      {% endif %}
    </div>
  {% endfor %}
    <input type="submit" value="로그인" class="btn btn-primary">
  </form>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
<h1>{{person.username}}'s 프로필</h1>
<div class="mb-3">
{% if request.user == person %}
  <a href="{% url 'accounts:update' %}" class="btn btn-outline-info">정보 수정</a>
  <a href="{% url 'accounts:change_password'%}" class="btn btn-outline-warning">비밀번호 변경</a>
{% endif %}
</div>
<p>
  팔로잉 수 : {{ person.followings.all|length }} / 팔로워 수 : {{ person.followers.all|length}}
</p>
<form action="{% url 'accounts:follows' person.pk %}" method="POST">
  {% csrf_token %}
  {% if request.user != person %}
    {% if request.user.is_authenticated %}
      {% if request.user in person.followers.all %}
        <input type="submit" value="Unfollow" class="btn btn-outline-danger">
      {% else %}
        <input type="submit" value="Follow" class="btn btn-outline-primary">
      {% endif %}
    {% else %}
      <input type="submit" value="Follow" class="btn disabled">
    {% endif %}
  {% endif %}
</form>
<hr>
<h2>작성한 글</h2>
{% for post in person.post_set.all %}
<div>
  <p>
    제목 - 
    <a href='{% url 'posts:detail' post.pk %}'>{{ post.title }}</a>
  </p>
</div>
{% endfor %}
<hr>
<h2>팔로잉 목록</h2>
{% for following in person.followings.all %}
<div>
  <a href="{% url 'accounts:profile' following.username %}" class="user-link">{{ following.username }}</a>
</div>
{% empty %}
  <p>팔로잉 한 사람이 없습니다.</p>
{% endfor %}
<hr>
<h2>팔로워 목록</h2>
{% for follower in person.followers.all %}
<div>
  <a href="{% url 'accounts:profile' follower.username %}" class="user-link">{{ follower.username }}</a>
</div>
{% empty %}
  <p>팔로워 한 사람이 없습니다.</p>
{% endfor %}
<hr>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}
  <h1 class="mb-3">Signup</h1>
  <form action="{% url 'accounts:signup' %}" method="POST">
    {% csrf_token %}
    
    {% for field in form %}
    <div class="mb-3">
      {% if field.errors %}
      {{ field.errors }}
      {% endif %}
      <label for="id_{{ field.name }}" class="form-label">{{ field.label }}</label>
      {{ field }}
      {% if field.help_text %}
      {{ field.help_text }}
      {% endif %}
    </div>
    {% endfor %}
    <input type="submit" value="가입하기" class="btn btn-primary">
  </form>

{% endblock content %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% block content %}
<h1 class="mb-3">Update</h1>
<form action="{% url 'accounts:update' %}" method="post">
  {% csrf_token %}
    
  {% for field in form %}
    <div class="mb-3">
      {% if field.errors %}
        {{ field.errors }}
      {% endif %}
      <label for="id_{{ field.name }}" class="form-label">{{ field.label }}</label>
      {{ field }}
    </div>
  {% endfor %}
  <input type="submit" value="변경하기" class="btn btn-primary">
</form>
{% endblock content %}