accounts/urls.py
from . import views
from django.urls import path

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follows/', views.follows, name='follows'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from posts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.redirect_index),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from . import views
from django.urls import path

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:post_pk>/', views.detail, name='detail'),
    path('<int:post_pk>/answer/<str:answer>', views.answer, name='answer'),
    path('<int:post_pk>/likes/', views.post_like, name='post_like'),
    path('<int:post_pk>/comments/', views.comment_create, name='comment_create'),
    path('<int:post_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:post_pk>/comments/<int:comment_pk>/likes/', views.comment_like, name='comment_like'),
    path('<int:post_pk>/comments/<int:comment_pk>/update/', views.comment_update, name='comment_update'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Balance-Game</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% comment %} Font-awesom Icon {% endcomment %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
  <nav class="navbar bg-body shadow-sm sticky-top">
    <div class="container nav-aria">
      <a class="navbar-brand" href="{% url 'posts:index' %}"><i class="fa-solid fa-scale-balanced fs-3"></i></a>
      <div class="d-flex gap-2">
        {% if request.user.is_authenticated %}
        <div id="profile" class="position-relative">
          <button type="button" class="btn d-flex gap-2 align-items-center">
            <div class="profile-bg bg-body-secondary">
              <i class="fa-solid fa-user fs-5"></i>
            </div>
            <span class="fs-6">{{ request.user }}</span>
          </button>
          <div class="list-group position-absolute end-0 profile-list d-none">
            <a href="{% url 'accounts:profile' request.user.username %}" class="list-group-item">내 프로필</a>
            <a href="{% url 'accounts:logout' %}" class="list-group-item">로그아웃</a>
          </div>
        </div>
        {% else %}
        <a href="{% url 'accounts:login' %}" class="btn btn-primary">로그인</a>
        <a href="{% url 'accounts:signup' %}" class="btn btn-outline-primary">회원가입</a>
        {% endif %}
      </div>
    </div>
    
  </nav>
  <main class="container-fluid my-5">
    {% block content %}
    {% endblock content %}
  </main>
  
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script>
    const bodyTag = document.querySelector('body')
    
    try {
      const profileBtn = document.querySelector('#profile')
      const profileList = document.querySelector('.profile-list')
      profileBtn.addEventListener('click', (event) => {
        profileList.classList.remove('d-none')
      })

      bodyTag.addEventListener('mouseup', (event) => {
        if (!profileList.contains(event.target)) {
          profileList.classList.add('d-none')
        }
      })
    } catch(err) {
    }
    
  </script>
</body>
</html>