accounts/urls.py
from . import views
from django.urls import path

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follows/', views.follows, name='follows'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from posts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.redirect_index),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from . import views
from django.urls import path

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:post_pk>/', views.detail, name='detail'),
    path('<int:post_pk>/answer/<str:answer>', views.answer, name='answer'),
    path('<int:post_pk>/likes/', views.post_like, name='post_like'),
    path('<int:post_pk>/comments/', views.comment_create, name='comment_create'),
    path('<int:post_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:post_pk>/comments/<int:comment_pk>/likes/', views.comment_like, name='comment_like'),
    path('<int:post_pk>/comments/<int:comment_pk>/update/', views.comment_update, name='comment_update'),
]

posts/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=20)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')
    select1_content = models.CharField(max_length=20)
    select2_content = models.CharField(max_length=20)
    select1_user = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='select1')
    select2_user = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='select2')
    select1_image = ProcessedImageField(blank=True, upload_to='select_image',
                                        processors=[ResizeToFill(100,100)],
                                        format='PNG',
                                        options={'quality': 80})
    select2_image = ProcessedImageField(blank=True, upload_to='select_image',
                                        processors=[ResizeToFill(100,100)],
                                        format='PNG',
                                        options={'quality': 80})
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField()
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_comments')

posts/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    title = forms.CharField(
        label='제목',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'style': 'width:40%; min-width:300px;',
            }
        )
    )
    select1_content = forms.CharField(
        label='선택1',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'style': 'width:40%; min-width:300px;',
            }
        )
    )
    select2_content = forms.CharField(
        label='선택2',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'style': 'width:40%; min-width:300px;',
            }
        )
    )
    select1_image = forms.ImageField(
        label='선택1 이미지(선택사항)',
        widget=forms.ClearableFileInput(
            attrs={
                'class': 'form-control',
                'style': 'width:40%; min-width:300px',
            }
        ),
        required=False,
    )
    select2_image = forms.ImageField(
        label='선택2 이미지(선택사항)',
        widget=forms.ClearableFileInput(
            attrs={
                'class': 'form-control',
                'style': 'width:40%; min-width:300px',
            }
        ),
        required=False,
    )
    
    class Meta:
        model = Post
        fields = (
            'title', 
            'select1_content', 
            'select2_content', 
            'select1_image', 
            'select2_image',
            )
        
class CommentForm(forms.ModelForm):
    content = forms.CharField(
        label='댓글 작성하기',
        widget=forms.Textarea(
            attrs={
                'rows':'3',
                'style': 'width:400px;',
                'class':'form-control',
            }
        )
    )
    class Meta:
        model = Comment
        fields = ('content', )
        # widgets = {
        #     'content': forms.Textarea(attrs={'rows':'3',}),
        # }

class CommentUpdateForm(forms.ModelForm):
    content = forms.CharField(
        label='댓글 수정하기',
        widget=forms.Textarea(
            attrs={
                'rows':'3',
                'style':'width:400px;',
                'class':'form-control',
            }
        )
    )
    class Meta:
        model = Comment
        fields = ('content', )

posts/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from .models import Post, Comment
from .forms import PostForm, CommentForm, CommentUpdateForm
from django.contrib.auth.decorators import login_required
import json

# Create your views here.
def index(request):
    posts = Post.objects.all()
    context = {
        'posts': posts,
    }
    return render(request, 'posts/index.html', context)


def redirect_index(request):
    return redirect('posts:index')


@login_required
def create(request):
    if request.method == 'POST':
        form = PostForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('posts:index')
    else:
        form = PostForm()
        
    context = {
        'form': form,
    }
    return render(request, 'posts/create.html', context)


def detail(request, post_pk: int):
    post = Post.objects.get(pk=post_pk)
    comments = post.comment_set.all()
    comment_form = CommentForm()
    comment_updateform = CommentUpdateForm()
    context = {
        'post': post,
        'comment_form': comment_form,
        'comments': comments,
        'comment_updateform': comment_updateform,
    }
    return render(request, 'posts/detail.html', context)


@login_required
def answer(request, post_pk, answer):
    post = Post.objects.get(pk=post_pk)

    if request.user not in post.select1_user.all() and request.user not in post.select2_user.all():
        if answer == post.select1_content:
            post.select1_user.add(request.user)
        elif answer == post.select2_content:
            post.select2_user.add(request.user)
    
    return redirect('posts:detail', post_pk)


@login_required
def post_like(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    if post.like_users.filter(pk=request.user.pk).exists():
        post.like_users.remove(request.user)
        is_liked = False
    else:
        post.like_users.add(request.user)
        is_liked = True
    
    context = {
        'is_liked': is_liked,
        'likes_count': post.like_users.count(),
    }
    return JsonResponse(context)


@login_required
def comment_create(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.post = post
        comment.user = request.user
        comment.save()  
    return redirect('posts:detail', post.pk)


def comment_delete(request, post_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)

    if request.user == comment.user:
        comment.delete()
    return redirect('posts:detail', post_pk)
    
    
@login_required
def comment_like(request, post_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if comment.like_users.filter(pk=request.user.pk).exists():
        comment.like_users.remove(request.user)
        is_liked = False
    else:
        comment.like_users.add(request.user)
        is_liked = True
    context = {
        'is_liked': is_liked,
        'likes_count': comment.like_users.count(),
    }
    return JsonResponse(context)


def comment_update(request, post_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    
    if request.user == comment.user:
        if request.method == 'POST':
            r = list(request.POST.keys())
            js = json.loads(r[0])
            comment.content = js['content']
            comment.save()

    context = {
        'content': comment.content,
    }
    return JsonResponse(context)

posts/templates/posts/create.html
{% extends 'base.html' %}
{% block content %}
  <h1>Create</h1>

  <form action="{% url 'posts:create' %}" method="post" class="" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
    <div class="mb-3">
      <label for="{{ field.id_for_label }}">{{ field.label }}</label>
      {{ field }}
    </div>
    {% endfor %}
    <input type="submit" value="주제 생성" class="btn btn-primary">
  </form>
{% endblock content %}

posts/templates/posts/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <h1>Detail</h1>

  <p class="">
    작성자 - 
    <a href="{% url 'accounts:profile' post.user.username %}">{{ post.user }}</a>
  </p>
  <p class="">
    제목 - 
    {{ post.title }}
  </p>

  {% comment %} post.likes {% endcomment %}
  <div class="mb-2">
    <form id="post-likeform" data-post-id="{{ post.pk }}">
      {% csrf_token %}
      {% if request.user.is_authenticated %}
        {% if request.user in post.like_users.all %}
          <button type="submit" class="p-0 btn btn-link text-danger"><i class="bi bi-heart-fill"></i></button>
        {% else %}
          <button type="submit" class="p-0 btn btn-link text-danger"><i class="bi bi-heart"></i></button>
        {% endif %}
      {% else %}
        <button type="submit" class="p-0 btn btn-link text-danger" disabled="disabled"><i class="bi bi-heart"></i></button>  
      {% endif %}
      <span id="post-likescount">{{ post.like_users.count }}</span>
    </form>
  </div>

  <div class="d-flex justify-content-center">

    <div class="d-flex flex-column">
      {% if post.select1_image %}
      <img src="{{ post.select1_image.url }}" alt="image" class="select-image">
      {% else %}
      <img src="{% static 'no-img.jpg' %}" alt="no image" class="select-image">
      {% endif %}
      <form action="{% url 'posts:answer' post.pk post.select1_content %}" method="post">
        {% csrf_token %}
        <button type="submit" class="container-fluid rounded-3 btn btn-sm btn-primary ps-1 pe-1"
        {% if request.user in post.select1_user.all or request.user in post.select2_user.all %}
          disabled="disabled"
        {% endif %}
        >{{ post.select1_content }} - {{ post.select1_user.all.count }}</button>
      </form>
    </div>
  
    <div class="d-flex flex-column">
      {% if post.select2_image %}
        <img src="{{ post.select2_image.url }}" alt="image" class="select-image">
      {% else %}
        <img src="{% static 'no-img.jpg' %}" alt="no image" class="select-image">
      {% endif %}
      <form action="{% url 'posts:answer' post.pk post.select2_content %}" method="post">
        {% csrf_token %}
        <button type="submit" class="container-fluid rounded-3 btn btn-sm btn-secondary ps-1 pe-1"
        {% if request.user in post.select1_user.all or request.user in post.select2_user.all %}
          disabled="disabled"
        {% endif %}
        >{{ post.select2_content }} - {{ post.select2_user.all.count }}</button>
      </form>
    </div>

  </div>

  <hr>

  <form action="{% url 'posts:comment_create' post.pk %}" method="POST">
    {% csrf_token %}
    {% for field in comment_form %}
      <label for="{{ field.id_for_label }}">{{ field.label }}</label>
      {{ field }}
    {% endfor %}
    <input type="submit" value="댓글 작성" class="btn btn-sm btn-outline-primary mt-3">
  </form>

  <hr>

  {% for comment in comments %}
    <p>작성자 - {{ comment.user }}</p>
    <p id="comment-content-{{ comment.pk }}">{{ comment.content }}</p>
  
    <div class="mb-1">
    {% if request.user.is_authenticated %}
      <form class="comment-likeform" id="commentlike-{{ comment.pk }}" data-comment-id="{{ comment.pk }}" data-post-id="{{ post.pk }}">
      {% csrf_token %}
      {% if request.user in comment.like_users.all %}
        <button type="submit" class="p-0 btn btn-link text-danger"><i class="bi bi-heart-fill"></i></button>
      {% else %}
        <button type="submit" class="p-0 btn btn-link text-danger"><i class="bi bi-heart"></i></button>
      {% endif %}
    {% else %}
        <button type="submit" class="p-0 btn btn-link text-danger" disabled="disabled"><i class="bi bi-heart"></i></button> 
    {% endif %}
        <span class="like-{{ comment.pk }}">{{ comment.like_users.count }}</span>
      </form>
    </div>

  <div>
    {% if request.user == comment.user %}
      <div class="d-flex">
        <form action="{% url 'posts:comment_delete' post.pk comment.pk %}" method="POST" class="me-3">
          {% csrf_token %}
          <input type="submit" value="댓글 삭제" class="btn btn-sm btn-outline-danger" onclick="onDelete()">
        </form>
        <input type="button" value="댓글 수정" class="comment-edit-btn btn btn-sm btn-outline-primary" data-post-id="{{ post.pk }}" data-comment-id="{{ comment.pk }}">
      </div>
      <form class="comment-edit-form my-3" id="comment-edit-form-{{ comment.pk }}" data-post-id="{{ post.pk }}" data-comment-id="{{ comment.pk }}" hidden>
        {% csrf_token %}
        {% for field in comment_updateform %}
          <label for="{{ field.id_for_label }}">{{ field.label }}</label>
          {{ field }}
        {% endfor %}
        <input type="submit" value="수정" class="update btn btn-sm btn-outline-primary">
        <input type="button" value="취소" class="cancel btn btn-sm btn-outline-secondary" data-comment-id="{{ comment.pk }}">
      </form>
    {% endif %}
  </div>
  <hr>
  {% endfor %}
  <script>
    const postform = document.querySelector('#post-likeform')
    const commentforms = document.querySelectorAll('.comment-likeform')
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value

    // Post 좋아요
    postform.addEventListener('submit', function (event) {
      event.preventDefault()
      const postId = event.target.dataset.postId
      axios({
        method: 'post',
        url: `/posts/${postId}/likes/`,
        headers: {'X-CSRFToken': csrftoken},
      })
        .then((response) => {
          const isLiked = response.data.is_liked
          const postlikesCountTag = document.querySelector('#post-likescount')
          const postlikesCountData = response.data.likes_count
          const likeBtn = document.querySelector('#post-likeform > button[type=submit] > i')
          
          if (isLiked === true) {
            likeBtn.className = 'bi bi-heart-fill'
          } else {
            likeBtn.className = 'bi bi-heart'
          }
        
          postlikesCountTag.textContent = postlikesCountData
        })
        .catch((error) => {
          console.log(error.response)
        })
    })

    // Comment 좋아요
    commentforms.forEach((commentform) => {
      commentform.addEventListener('submit', function (event) {
        event.preventDefault()
        const commentId = event.target.dataset.commentId
        const postId = event.target.dataset.postId
        axios({
          method:'post',
          url:`/posts/${postId}/comments/${commentId}/likes/`,
          headers: {'X-CSRFToken': csrftoken},
        })
          .then((response) => {
            const isLiked = response.data.is_liked
            const commentLikesCountTag = document.querySelector(`.like-${commentId}`)
            const commentLikesCountData = response.data.likes_count
            const likeBtn = document.querySelector(`#commentlike-${commentId} > button[type=submit] > i`)
            
            if (isLiked) {
              likeBtn.className = 'bi bi-heart-fill'
            } else {
              likeBtn.className = 'bi bi-heart'
            }
            commentLikesCountTag.textContent = commentLikesCountData
          })
          .catch((error) => {
            console.log(error.response)
          })
      })

    })

    // 댓글 수정
    const commentUpdates = document.querySelectorAll('.comment-edit-btn')

    commentUpdates.forEach((comment) => {
      comment.addEventListener('click', (event) => {
        const commentId = event.target.dataset.commentId
        const commentUpdateDiv = document.querySelector(`#comment-edit-form-${commentId}`)
        const contentTextArea = document.querySelector(`#comment-edit-form-${commentId}>textarea`)
        commentUpdateDiv.hidden = false
        contentTextArea.value = document.querySelector(`#comment-content-${commentId}`).textContent
      })
    })
    
    const commentUpdateConfirms = document.querySelectorAll('.comment-edit-form')
    commentUpdateConfirms.forEach((updateBtn) => {
      updateBtn.addEventListener('submit', (event) => {
        event.preventDefault()
        const postId = event.target.dataset.postId
        const commentId = event.target.dataset.commentId
        const data = {
          content: document.querySelector(`#comment-edit-form-${commentId}>textarea`).value,
        }
        axios({
          method:'post',
          url:`/posts/${postId}/comments/${commentId}/update/`,
          headers: {'X-CSRFToken': csrftoken,},
          data: JSON.stringify(data),
        })
          .then((response) => {
            if (window.confirm('댓글 수정하시겠습니까?')) {
              updateBtn.hidden = true
              document.querySelector(`#comment-content-${commentId}`).textContent = data['content']
            }
          })
          .catch((error) => {
            console.log(error.response)
          })
      })
    })

    const commentUpdateCancels = document.querySelectorAll('.comment-edit-form>.cancel')
    commentUpdateCancels.forEach((cancelBtn) => {
      cancelBtn.addEventListener('click', (event) => {
        const commentId = event.target.dataset.commentId
        const commentUpdateForm = document.querySelector(`#comment-edit-form-${commentId}`)
        commentUpdateForm.hidden = true
      })
    })

    // 댓글 삭제
    const onDelete = () => {
      if (window.confirm('삭제하시겠습니까?')) {
        alert('삭제되었습니다.')
      } 
    }
  </script>
{% endblock content %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>Index</h1>
  
  <div class="mb-3">
    {% if request.user.is_authenticated %}
    <span><a href="{% url 'accounts:profile' request.user.username %}" class="user-link">
    {{ request.user }}</a> 님 안녕하세요 ! </span>
    {% endif %}
  </div>
  <div class="mb-3">
    <a href="{% url 'posts:create' %}" class="btn btn-outline-success">주제 생성</a>
  </div>
  <hr>

  {% for post in posts %}
    <p>
      작성자 - 
      <a href="{% url 'accounts:profile' post.user.username %}">{{ post.user }}</a>
    </p>
    <p>
      <span class="">제목 - </span>
      <a href='{% url 'posts:detail' post.pk %}'>
        {{ post.title }}
      </a>
    </p>

    <hr>

  {% endfor %}
{% endblock content %}